server:
  port: 8080

spring:
  application:
    name: springcloud-fabric-test
  datasource:
    # 当前数据源操作类型
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    # mysql驱动类
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
